# Configuration for equity pairs research

# Universe and data settings
universe: "sp100"
start_date: "2020-01-01"
end_date: "2023-01-01"
timeframe: "1d"

# Research parameters
min_lookback: 252
max_pairs: 30
train_ratio: 0.6
test_ratio: 0.2
validation_ratio: 0.2

# Statistical tests - stricter for equities
cointegration:
  significance_level: 0.01
  min_correlation: 0.6
  max_half_life: 20.0
  min_cointegration_score: 0.8

# Signal generation - more conservative
signals:
  entry_z_threshold: 2.5
  exit_z_threshold: 0.3
  max_position_size: 0.8
  min_half_life: 2.0
  max_half_life: 20.0
  regime_filter: true

# Backtesting - realistic costs for equities
backtest:
  initial_capital: 1000000.0
  commission_rate: 0.001
  slippage_rate: 0.0003
  borrow_rate: 0.025
  max_leverage: 1.5
  min_trade_size: 5000.0

# Risk management - conservative for equities
risk:
  max_leverage: 1.5
  max_position_size: 0.15
  max_portfolio_exposure: 0.8
  target_volatility: 0.12
  var_confidence: 0.05
  max_drawdown: 0.15

# Sector filtering
sector_filter: true
same_sector_only: true

# Random seed for reproducibility
seed: 42
